version: '3.9'

services:
  database:
    image: mysql
    container_name: banco_oficina
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'oficina'
    ports:
      - '3306:3306'
